services:
  mysql:
    container_name: mysql
    image: mariadb:11
    restart: always
    env_file:
      - .env
    environment:
      # Generate a random root password so we don't need to manage one.
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      # Bootstrap the app database + user from .env values:
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mydatabase:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u$${MARIADB_USER} -p$${MARIADB_PASSWORD} --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=ethan.villalovoz@gmail.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio

volumes:
  mydatabase:
  nginx_secrets:

